[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "python-jsonlogic"
version = "0.1.0"
description = "An extensible and sane implementation of JsonLogic"
readme = "README.rst"
authors = [
    {name = "Victorien", email = "contact@vctrn.dev"}
]
license = 'MIT'
license-files = ['LICENSE']
requires-python = ">=3.10"
classifiers = [
    "Development Status :: 4 - Beta",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Typing :: Typed",
    "Intended Audience :: Developers",
    "Topic :: Software Development :: Libraries :: Python Modules",
]
dependencies = [
    "typing-extensions>=4.10.0; python_version < '3.13'",
]

[dependency-groups]
dev = [
    "pyright",
    "ruff",
    "pytest>=8.4.0",
    "tomli",
    "ruff>=0.11.3",
    "tox>=4.25.0",
    "tox-gh>=1.5.0",
    "tox-uv>=1.25.0",
]
docs = [
    "furo",
    "sphinx",
    "sphinx-lint",
    "sphinx-paramlinks",
]


[tool.hatch.build.targets.wheel]
packages = ["src/jsonlogic"]

[tool.uv]
default-groups = ['dev']
required-version = ">=0.9.0"

[tool.ruff]
src = ["src"]
target-version = "py310"
line-length = 120

[tool.ruff.lint]
typing-modules = ["jsonlogic._compat"]
preview = true
explicit-preview-rules = true
select = [
    "E",      # pycodestyle (E)
    "W",      # pycodestyle (W)
    "F",      # Pyflakes
    "UP",     # pyupgrade
    "I",      # isort
    "PL",     # Pylint
    "RUF",    # Ruff
    "RUF022", # Ruff-preview
    "YTT",    # flake8-2020
    "B",      # flake8-bugbear
    "C4",     # flake8-comprehensions
    "T10",    # flake8-debugger
    "FA",     # flake8-future-annotations
    "PIE",    # flake8-pie
    "T20",    # flake8-print
    "RSE",    # flake8-raise
    "PTH",    # flake8-use-pathlib
]
ignore = [
    "PLR2004",
    "PLR0911",
]

[tool.ruff.lint.isort]
known-first-party = ["jsonlogic"]

[tool.pytest.ini_options]
pythonpath = "src"

[tool.tox]
requires = ["tox>=4.21"]
env_list = ["py310", "py311", "py312", "py314"]

[tool.tox.env_run_base]
description = "Run test under {base_python}"
runner = "uv-venv-lock-runner"
dependency_groups = ["dev"]
uv_python_preference = "only-managed"
uv_sync_flags = ["--no-python-downloads"]
commands = [["pytest"]]

[tool.tox.gh.python]
"3.10" = ["py310"]
"3.11" = ["py311"]
"3.12" = ["py312"]
"3.13" = ["py313"]
"3.14" = ["py314"]
